spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j9b202.p.ssafy.io:3350/newsum?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssafyb202
    password: ssafy
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

# JPA log
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8080
  max-http-header-size: 2MB

